name: Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-20.04
    container: 
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    container: 
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/tests/e2e/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # api-tests:
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node16.17.1-chrome106-ff105-edge
  #     options: --user 1001
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Download the build folders
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: build

  #     - name: "API Tests"
  #       uses: cypress-io/github-action@v4
  #       with:
  #         start: npm run start:ci
  #         wait-on: "http://localhost:3000"
  #         wait-on-timeout: 120
  #         browser: chrome
  #         spec: cypress/tests/api/*
  #       env:
  #         # Recommended: pass the GitHub token lets this action correctly
  #         # determine the unique run id necessary to re-run the checks
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}